#!/usr/bin/env python3
from __future__ import annotations
"""generate_test_mapping.py — scan Python test files and Rust test names,
produce TEST_MAPPING.toml mapping every Python test to its Rust counterpart(s).

Usage:
    python harness/generate_test_mapping.py [--update]

Without --update: prints the mapping to stdout.
With --update: writes TEST_MAPPING.toml (preserving manual Rust mappings).
"""
import ast
import os
import re
import subprocess
import sys
try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # pip install tomli for Python <3.11
    except ModuleNotFoundError:
        tomllib = None  # Will skip loading existing mapping if unavailable
from collections import OrderedDict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TESTS_DIR = REPO_ROOT / "tests"
MAPPING_FILE = REPO_ROOT / "TEST_MAPPING.toml"


def scan_python_tests() -> dict[str, list[str]]:
    """Parse all *Test.py files and extract test method names grouped by class."""
    result: dict[str, list[str]] = {}

    for test_file in sorted(TESTS_DIR.glob("*Test.py")):
        with open(test_file) as f:
            try:
                tree = ast.parse(f.read(), filename=str(test_file))
            except SyntaxError:
                print(f"  WARN: Could not parse {test_file.name}", file=sys.stderr)
                continue

        for node in ast.walk(tree):
            # Match classes like RangeSetTest and also parameterized variants
            # like CLIClushTest_A / CLINodesetGroupResolverTest1
            if isinstance(node, ast.ClassDef) and "Test" in node.name:
                methods = []
                for item in node.body:
                    if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        if item.name.startswith("test"):
                            methods.append(item.name)
                if methods:
                    result[node.name] = methods

    return result


def scan_rust_tests() -> list[str]:
    """Run `cargo test -- --list` on the core and CLI crates, extract test names."""
    tests = []
    for package in ("consortium-crate", "consortium-cli"):
        try:
            proc = subprocess.run(
                ["cargo", "test", "-p", package, "--", "--list"],
                capture_output=True,
                text=True,
                cwd=str(REPO_ROOT),
                timeout=60,
            )
            for line in proc.stdout.splitlines():
                line = line.strip()
                if line.endswith(": test"):
                    tests.append(line.removesuffix(": test"))
        except (subprocess.TimeoutExpired, FileNotFoundError):
            print(f"  WARN: Could not run cargo test --list for {package}", file=sys.stderr)
    return sorted(set(tests))


def python_to_rust_name(py_class: str, py_method: str) -> str:
    """Convert Python test name to expected Rust convention.

    RangeSetTest::testSimple -> range_set::tests::test_simple
    """
    # Class -> module: RangeSetTest -> range_set, NodeSetTest -> node_set
    module = py_class.removesuffix("Test")
    # CamelCase to snake_case
    module = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", module).lower()
    # Also handle sequences like "ND" -> "_nd"
    module = re.sub(r"([A-Z]+)", lambda m: "_" + m.group(1).lower(), module).lstrip("_")
    # Fix double underscores
    module = re.sub(r"_+", "_", module)

    # Method: testSimple -> test_simple, test_ior -> test_ior
    method = py_method
    if not method.startswith("test_"):
        # camelCase to snake_case: testSimple -> test_simple
        method = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", method).lower()

    return f"{module}::tests::{method}"


def load_existing_mapping() -> dict:
    """Load existing TEST_MAPPING.toml if it exists."""
    if MAPPING_FILE.exists() and tomllib is not None:
        with open(MAPPING_FILE, "rb") as f:
            return tomllib.load(f)
    return {}


def format_toml_value(val) -> str:
    """Format a Python value as TOML."""
    if isinstance(val, str):
        return f'"{val}"'
    if isinstance(val, list):
        if not val:
            return "[]"
        if len(val) == 1:
            return f'["{val[0]}"]'
        inner = ", ".join(f'"{v}"' for v in val)
        return f"[{inner}]"
    return str(val)


def generate_mapping(update: bool = False):
    """Generate the full mapping."""
    python_tests = scan_python_tests()
    rust_tests = scan_rust_tests()
    existing = load_existing_mapping() if update else {}

    # Stats
    total_py = sum(len(v) for v in python_tests.values())
    mapped = 0
    unmapped = 0

    lines = []
    lines.append("# TEST_MAPPING.toml — auto-generated by harness/generate_test_mapping.py")
    lines.append("# Maps every upstream Python test to its Rust counterpart(s).")
    lines.append("# Empty arrays mean the test is not yet ported to Rust.")
    lines.append("#")
    lines.append("# Regenerate: python harness/generate_test_mapping.py --update")
    lines.append("")

    lines.append("[upstream]")
    ref = (REPO_ROOT / "UPSTREAM_REF").read_text().strip() if (REPO_ROOT / "UPSTREAM_REF").exists() else "unknown"
    lines.append(f'repo = "cea-hpc/clustershell"')
    lines.append(f'ref = "{ref}"')
    lines.append("")

    for py_class, py_methods in sorted(python_tests.items()):
        lines.append(f"[{py_class}]")

        for method in py_methods:
            # Check if there's a manual mapping in existing file
            existing_mapping = None
            if py_class in existing and method in existing[py_class]:
                existing_mapping = existing[py_class][method]

            if existing_mapping:
                # Preserve non-empty manual mapping (empty arrays are treated
                # as "not yet mapped" and re-run through auto-detection so the
                # mapping improves as new Rust tests land)
                rust_names = existing_mapping if isinstance(existing_mapping, list) else [existing_mapping]
            else:
                # Auto-detect: check if the conventional Rust name exists
                expected = python_to_rust_name(py_class, method)
                if expected in rust_tests:
                    rust_names = [expected]
                else:
                    # Try fuzzy: look for rust tests containing the method name
                    method_snake = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", method).lower()
                    matches = [t for t in rust_tests if method_snake in t]
                    rust_names = matches if matches else []

            if rust_names:
                mapped += 1
            else:
                unmapped += 1

            lines.append(f"{method} = {format_toml_value(rust_names)}")

        lines.append("")

    # Append unmatched Rust tests section
    all_mapped_rust = set()
    for py_class, py_methods in python_tests.items():
        for method in py_methods:
            expected = python_to_rust_name(py_class, method)
            if expected in rust_tests:
                all_mapped_rust.add(expected)
            # Also check existing
            if py_class in existing and method in existing[py_class]:
                val = existing[py_class][method]
                if isinstance(val, list):
                    all_mapped_rust.update(val)
                elif isinstance(val, str):
                    all_mapped_rust.add(val)

    extra_rust = sorted(set(rust_tests) - all_mapped_rust)
    if extra_rust:
        lines.append("[_extra_rust_tests]")
        lines.append("# Rust tests with no direct Python counterpart (extra coverage)")
        for t in extra_rust:
            lines.append(f'# {t}')
        lines.append("")

    # Summary
    lines.append(f"# Summary: {total_py} Python tests, {mapped} mapped, {unmapped} unmapped, {len(extra_rust)} extra Rust tests")

    output = "\n".join(lines) + "\n"

    if update:
        with open(MAPPING_FILE, "w") as f:
            f.write(output)
        print(f"Wrote {MAPPING_FILE}")
        print(f"  {total_py} Python tests, {mapped} mapped to Rust, {unmapped} unmapped, {len(extra_rust)} extra Rust tests")
    else:
        print(output)


if __name__ == "__main__":
    update = "--update" in sys.argv
    generate_mapping(update=update)
